Update docs example
swalladge/wallabag-api pull request #12
Opened 2021-04-10 10:43 UTC by mx-psi

- Remove `notrust` from code block (since it is actually Rust code)
- Update example based on `examples/get_entries.rs`

2021-04-10 10:50 UTC, mx-psi commented
CI is failing because we either need to merge #11 or pin the `surf` version by setting `surf = "=2.0.0-alpha.0"`

2021-04-20 22:34 UTC, swalladge requested changes

2021-04-20 22:34 UTC, swalladge commented on src/lib.rs
> +//! ```
This was labelled `notrust` so that it wouldn't be run in tests - maybe there's a better method to exclude rust code from doctests now?  We can't run it in a test, because it's an example of making a network request that requires valid credentials and running wallabag server.

2021-04-21 06:39 UTC, mx-psi commented on src/lib.rs
> +//! ```
>  maybe there's a better method to exclude rust code from doctests now? 

It looks like [there is](https://doc.rust-lang.org/rustdoc/documentation-tests.html#attributes): `no_run` should try to build the example but not run it (which I think is what makes sense here).

2021-04-21 07:01 UTC, swalladge commented on src/lib.rs
> +//! ```
Perfect :ok_hand:

2021-04-21 07:01 UTC, swalladge approved these changes

2021-04-21 07:02 UTC, swalladge commented
@mx-psi perfect! Would you mind rebasing and squashing your changes, and I'll merge right away. :)

2021-04-21 07:11 UTC, mx-psi commented
Done!

2021-04-21 07:17 UTC, merged

2021-04-21 07:17 UTC, swalladge commented
Thanks for your contributions @mx-psi ! :grinning: 

Out of curiousity, what is your use case for this library? :)

2021-04-21 07:23 UTC, mx-psi commented
> Out of curiousity, what is your use case for this library? :)

I publish a list of interesting things I read every couple months ([see here for last year, mostly in English](https://codual.github.io/log/2020/)). I had a script to fetch my favourite articles from Pocket and create a first draft of the list. Since I have switched to using Wallabag I am rewriting it now using this library

2021-04-21 07:25 UTC, swalladge commented
@mx-psi nice! Well I'm glad this is useful to you.

v0.4.0 published to crates.io and tagged in git btw. :)